### PR TITLE
Add NEAR example

### PR DESCRIPTION
**Pull request by AndWa**
- [X] Add NEAR example for contract call
- [X] Created README for NEAR examples directory
- [X] Created README for NEAR contract call example
- [X] Updated project README to include link to NEAR examples
- [X] Add NEAR example test

All tests are passing.

NEAR tests

### CODE REVIEW

**Review by re1ro — APPROVED** [review]

**Review by canhtrinh — APPROVED** [review]

**Review by npty — APPROVED** [review]

**Comment by npty** [comment]
@AndWa can you fix failed tests? i guess you need to increase the timeout.

**Comment by AndWa** [comment]
This is a new error. I will investigate, fix and update the request.

Sorry about this.

**Comment by AndWa** [comment]
Hi @npty :) 

- I updated the test timeout for all tests because for some reason EVM test failed with timeout for me locally
- Removed node_modules and ran all the steps from the github workflow in a clean directory
- Tests were able to pass

Axelar-test

I am not sure why did the last build fail saying that `createAccountAndDeployContract` was called on an undefined. I don't know is it possible that github workflow `npm ci` command did not pull all the packages..

If possible let's try to run the workflow again and see if it is going to be okay now.

**Comment by npty** [comment]
> Hi @npty :)
> 
> * I updated the test timeout for all tests because for some reason EVM test failed with timeout for me locally
> * Removed node_modules and ran all the steps from the github workflow in a clean directory
> * Tests were able to pass
> 
> Axelar-test
> 
> I am not sure why did the last build fail saying that `createAccountAndDeployContract` was called on an undefined. I don't know is it possible that github workflow `npm ci` command did not pull all the packages..
> 
> If possible let's try to run the workflow again and see if it is going to be okay now.

I've triggered the workflow to run again, still got the error you mentioned :(
```
 1) Check Examples Execution
       NEAR Examples
         call-contract:
     TypeError: Cannot read properties of undefined (reading 'createAccountAndDeployContract')
      at deployNearContract (examples/near/call-contract/index.js:20:43)
      at Object.execute (examples/near/call-contract/index.js:57:32)
      at async executeNearExample (scripts/libs/execute.js:28:5)
      at async Context.<anonymous> (examples/tests/checkExamples.js:70:17)
```

Btw, why there're lot of changes in `package-lock.json` even dependencies in `package.json remain unchanged.

**Pull request closed without merging**
